import Fastify from "fastify";
import { PROJECT_HEARMES_SUB_DIMENSIONS, projectHearmesQuestionsForRole } from "./lib/instrument.js";

type Role = "student" | "faculty" | "executive_leadership" | "administrative_staff" | "programming_staff" | "finance_staff";
const roles: { id: Role; label: string }[] = [
  { id: "student", label: "Student" }, { id: "faculty", label: "Faculty" }, { id: "executive_leadership", label: "Executive Leadership" }, { id: "administrative_staff", label: "Administrative Staff" }, { id: "programming_staff", label: "Programming Staff" }, { id: "finance_staff", label: "Finance Staff" }
];
const subDimensions = PROJECT_HEARMES_SUB_DIMENSIONS.map((item) => [item.id, item.label, item.dimensionId] as const);
const questionBank = Object.fromEntries(roles.map(({ id }) => [id, projectHearmesQuestionsForRole(id)]));
const action: Record<string, string> = Object.fromEntries(PROJECT_HEARMES_SUB_DIMENSIONS.map((item) => [item.id, `Create one focused, role-relevant next step for ${item.label}.`]));

const page = `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Project HEARMES Demo</title><style>
*{box-sizing:border-box}body{margin:0;background:#f5f7fb;color:#172033;font:16px system-ui,-apple-system,sans-serif}.wrap{max-width:920px;margin:40px auto;padding:0 20px}.card{background:#fff;border:1px solid #e4e8f0;border-radius:16px;padding:28px;box-shadow:0 8px 30px #1720330c}h1{margin:0 0 8px;font-size:30px}h2{margin-top:0}p{color:#56627a;line-height:1.55}.tag{color:#3667d6;background:#edf3ff;padding:5px 9px;border-radius:99px;font-size:13px;font-weight:650;display:inline-block}select,button{font:inherit;padding:11px 13px;border-radius:9px;border:1px solid #ccd4e3}select{width:100%;margin:12px 0 20px;background:#fff}button{background:#245ad5;color:#fff;border:0;font-weight:700;cursor:pointer}button:hover{background:#1d4dbd}.hidden{display:none}.progress{height:8px;background:#e7ebf3;border-radius:99px;margin:18px 0}.progress i{display:block;height:100%;background:#2d70d7;border-radius:99px}.choices{display:flex;gap:8px;flex-wrap:wrap;margin-top:24px}.choices button{background:#fff;color:#245ad5;border:1px solid #b8c9ef;min-width:70px}.choices button:hover,.choices button.selected{background:#245ad5;color:#fff}.dim{margin:14px 0}.bar{height:11px;background:#e8edf4;border-radius:99px;overflow:hidden}.bar i{display:block;height:100%;background:#3d78d7}.score{font-size:44px;font-weight:800;color:#245ad5}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:14px}.rec{border-left:4px solid #e5ab36;padding:12px 14px;background:#fffbf2;margin:10px 0}.muted{font-size:13px;color:#7a879c}
</style></head><body><main class="wrap"><section id="welcome" class="card"><span class="tag">Interactive local demo</span><h1>Project HEARMES</h1><p>Try the role-adaptive assessment flow. This demo stores nothing and runs entirely in memory; the production app uses the Postgres API.</p><label for="role">Your stakeholder role</label><select id="role"></select><button onclick="start()">Start assessment</button></section><section id="assessment" class="card hidden"><span id="counter" class="tag"></span><div class="progress"><i id="progress"></i></div><p id="dimension" class="muted"></p><h2 id="question"></h2><p>Choose the option that best reflects your current experience.</p><div class="choices" id="choices"></div></section><section id="report" class="card hidden"><span class="tag">Your readiness report</span><h1>Project HEARMES Results</h1><div class="score" id="overall"></div><p id="summary"></p><h2>Dimension scores</h2><div id="dimensions"></div><h2>Priority actions</h2><div id="actions"></div><button onclick="location.reload()">Start again</button></section></main><script src="/questions.js"></script><script>
const roles=${JSON.stringify(roles)}, subs=${JSON.stringify(subDimensions)}, advice=${JSON.stringify(action)}; let role, questions=[], answers=[], index=0; const $=id=>document.getElementById(id); roles.forEach(r=>$('role').insertAdjacentHTML('beforeend','<option value="'+r.id+'">'+r.label+'</option>'));
function start(){role=$('role').value;questions=window.HEAIR_QUESTION_BANK[role]||[];$('welcome').classList.add('hidden');$('assessment').classList.remove('hidden');renderQuestion()}
function renderQuestion(){const s=questions[index];$('counter').textContent='Question '+(index+1)+' of '+questions.length;$('progress').style.width=((index)/questions.length*100)+'%';$('dimension').textContent=s.dimension.label;$('question').textContent=s.prompt;$('choices').innerHTML=[1,2,3,4,5].map(n=>'<button onclick="answer('+n+')">'+n+'<br><small>'+['Low','Fair','Moderate','Good','High'][n-1]+'</small></button>').join('')}
function answer(v){answers.push(v);index++;if(index<questions.length)renderQuestion();else showReport()}
function showReport(){$('assessment').classList.add('hidden');$('report').classList.remove('hidden');const scores=answers.map(x=>(x-1)*25), overall=scores.reduce((a,b)=>a+b,0)/scores.length;$('overall').textContent=overall.toFixed(1)+' / 100';const weak=[...scores.keys()].sort((a,b)=>scores[a]-scores[b]).slice(0,3);$('summary').textContent='Your assessment highlights the strongest opportunities for improvement in '+weak.map(i=>questions[i].subDimension.label).join(', ')+'.';const groups={};questions.forEach((s,i)=>(groups[s.dimension.label]??=[]).push(scores[i]));$('dimensions').innerHTML=Object.entries(groups).map(([d,v])=>{let n=v.reduce((a,b)=>a+b,0)/v.length;return '<div class="dim"><b>'+d+'</b> <span class="muted">'+n.toFixed(0)+'/100</span><div class="bar"><i style="width:'+n+'%"></i></div></div>'}).join('');$('actions').innerHTML=weak.map(i=>'<div class="rec"><b>Improve '+questions[i].subDimension.label+'</b><br>'+advice[questions[i].subDimension.id]+'</div>').join('')}
</script></body></html>`;

const app = Fastify();
const questionScript = `window.HEAIR_QUESTION_BANK=${JSON.stringify(questionBank)};`;
app.get("/", async (_request, reply) => reply.type("text/html").send(page));
app.get("/questions.js", async (_request, reply) => reply.type("application/javascript").send(questionScript));
app.get("/health", async () => ({ status: "ok", mode: "in-memory-demo" }));
await app.listen({ port: Number(process.env.PORT ?? 3001), host: "127.0.0.1" });
console.log("Project HEARMES demo available at http://127.0.0.1:3001");
