import Fastify from "fastify";

type Role = "student" | "faculty" | "administrator_leadership" | "it_staff" | "academic_business_affairs_staff";
const roles: { id: Role; label: string }[] = [
  { id: "student", label: "Student" }, { id: "faculty", label: "Faculty" }, { id: "administrator_leadership", label: "Administrator / Leadership" }, { id: "it_staff", label: "IT Staff" }, { id: "academic_business_affairs_staff", label: "Academic / Business Affairs Staff" }
];
const subDimensions = [
  ["policy_compliance", "Policy & Compliance", "Governance & Strategy"], ["ai_governance_access", "AI Governance & Access", "Governance & Strategy"], ["leadership_resourcing", "Leadership & Resourcing", "Governance & Strategy"], ["monitoring_evaluation", "Monitoring & Evaluation", "Governance & Strategy"],
  ["infrastructure_privacy_security", "Infrastructure, Privacy & Security", "Systems & Infrastructure"], ["data", "Data", "Systems & Infrastructure"], ["ai_integration_use_cases", "AI Integration & Use Cases", "Systems & Infrastructure"],
  ["trust_transparency", "Trust & Transparency", "Culture"], ["ethics_responsible_use", "Ethics & Responsible Use", "Culture"], ["stakeholder_engagement_awareness", "Stakeholder Engagement & Awareness", "Culture"],
  ["ai_literacy", "AI Literacy", "Education"], ["expertise_development", "Expertise Development", "Education"]
] as const;
const questionLead: Record<Role, string> = {
  student: "As a student, how would you rate your readiness for:", faculty: "As faculty, how would you rate your readiness for:", administrator_leadership: "As an institutional leader, how would you rate your readiness for:", it_staff: "As IT staff, how would you rate your readiness for:", academic_business_affairs_staff: "In your operational role, how would you rate your readiness for:"
};
const action: Record<string, string> = { policy_compliance: "Review and communicate practical AI policy and escalation guidance.", ai_governance_access: "Publish a simple and equitable pathway for AI tool approval and access.", leadership_resourcing: "Assign accountable leadership and fund a focused improvement plan.", monitoring_evaluation: "Measure AI outcomes, risks, and stakeholder feedback on a regular cadence.", infrastructure_privacy_security: "Review approved AI tools for privacy, security, accessibility, and data protection.", data: "Document data quality, stewardship, access controls, and permissible AI data flows.", ai_integration_use_cases: "Prioritize a small set of measurable, responsibly governed AI use cases.", trust_transparency: "Explain where AI is used, what it does, its limits, and how people can challenge outcomes.", ethics_responsible_use: "Provide scenario-based responsible-AI guidance for this role.", stakeholder_engagement_awareness: "Create recurring channels for stakeholder feedback, communication, and awareness.", ai_literacy: "Offer role-relevant AI literacy on capabilities, limitations, risk, and verification.", expertise_development: "Create advanced learning pathways and communities of practice." };

const page = `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>HEAIR Readiness Demo</title><style>
*{box-sizing:border-box}body{margin:0;background:#f5f7fb;color:#172033;font:16px system-ui,-apple-system,sans-serif}.wrap{max-width:920px;margin:40px auto;padding:0 20px}.card{background:#fff;border:1px solid #e4e8f0;border-radius:16px;padding:28px;box-shadow:0 8px 30px #1720330c}h1{margin:0 0 8px;font-size:30px}h2{margin-top:0}p{color:#56627a;line-height:1.55}.tag{color:#3667d6;background:#edf3ff;padding:5px 9px;border-radius:99px;font-size:13px;font-weight:650;display:inline-block}select,button{font:inherit;padding:11px 13px;border-radius:9px;border:1px solid #ccd4e3}select{width:100%;margin:12px 0 20px;background:#fff}button{background:#245ad5;color:#fff;border:0;font-weight:700;cursor:pointer}button:hover{background:#1d4dbd}.hidden{display:none}.progress{height:8px;background:#e7ebf3;border-radius:99px;margin:18px 0}.progress i{display:block;height:100%;background:#2d70d7;border-radius:99px}.choices{display:flex;gap:8px;flex-wrap:wrap;margin-top:24px}.choices button{background:#fff;color:#245ad5;border:1px solid #b8c9ef;min-width:70px}.choices button:hover,.choices button.selected{background:#245ad5;color:#fff}.dim{margin:14px 0}.bar{height:11px;background:#e8edf4;border-radius:99px;overflow:hidden}.bar i{display:block;height:100%;background:#3d78d7}.score{font-size:44px;font-weight:800;color:#245ad5}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:14px}.rec{border-left:4px solid #e5ab36;padding:12px 14px;background:#fffbf2;margin:10px 0}.muted{font-size:13px;color:#7a879c}
</style></head><body><main class="wrap"><section id="welcome" class="card"><span class="tag">Interactive local demo</span><h1>HEAIR Readiness Platform</h1><p>Try the role-adaptive assessment flow. This demo stores nothing and runs entirely in memory; the production app uses the Postgres API.</p><label for="role">Your stakeholder role</label><select id="role"></select><button onclick="start()">Start assessment</button></section><section id="assessment" class="card hidden"><span id="counter" class="tag"></span><div class="progress"><i id="progress"></i></div><p id="dimension" class="muted"></p><h2 id="question"></h2><p>Choose the option that best reflects your current experience.</p><div class="choices" id="choices"></div></section><section id="report" class="card hidden"><span class="tag">Your readiness report</span><h1>HEAIR Results</h1><div class="score" id="overall"></div><p id="summary"></p><h2>Dimension scores</h2><div id="dimensions"></div><h2>Priority actions</h2><div id="actions"></div><button onclick="location.reload()">Start again</button></section></main><script>
const roles=${JSON.stringify(roles)}, subs=${JSON.stringify(subDimensions)}, advice=${JSON.stringify(action)}; let role, answers=[], index=0; const $=id=>document.getElementById(id); roles.forEach(r=>$('role').insertAdjacentHTML('beforeend','<option value="'+r.id+'">'+r.label+'</option>'));
function start(){role=$('role').value;$('welcome').classList.add('hidden');$('assessment').classList.remove('hidden');renderQuestion()}
function renderQuestion(){const s=subs[index];$('counter').textContent='Question '+(index+1)+' of '+subs.length;$('progress').style.width=((index)/subs.length*100)+'%';$('dimension').textContent=s[2];$('question').textContent=${JSON.stringify(questionLead)}[role]+' '+s[1]+'?';$('choices').innerHTML=[1,2,3,4,5].map(n=>'<button onclick="answer('+n+')">'+n+'<br><small>'+['Low','Fair','Moderate','Good','High'][n-1]+'</small></button>').join('')}
function answer(v){answers.push(v);index++;if(index<subs.length)renderQuestion();else showReport()}
function showReport(){$('assessment').classList.add('hidden');$('report').classList.remove('hidden');const scores=answers.map(x=>(x-1)*25), overall=scores.reduce((a,b)=>a+b,0)/scores.length;$('overall').textContent=overall.toFixed(1)+' / 100';const weak=[...scores.keys()].sort((a,b)=>scores[a]-scores[b]).slice(0,3);$('summary').textContent='Your assessment highlights the strongest opportunities for improvement in '+weak.map(i=>subs[i][1]).join(', ')+'.';const groups={};subs.forEach((s,i)=>(groups[s[2]]??=[]).push(scores[i]));$('dimensions').innerHTML=Object.entries(groups).map(([d,v])=>{let n=v.reduce((a,b)=>a+b,0)/v.length;return '<div class="dim"><b>'+d+'</b> <span class="muted">'+n.toFixed(0)+'/100</span><div class="bar"><i style="width:'+n+'%"></i></div></div>'}).join('');$('actions').innerHTML=weak.map(i=>'<div class="rec"><b>Improve '+subs[i][1]+'</b><br>'+advice[subs[i][0]]+'</div>').join('')}
</script></body></html>`;

const app = Fastify();
app.get("/", async (_request, reply) => reply.type("text/html").send(page));
app.get("/health", async () => ({ status: "ok", mode: "in-memory-demo" }));
await app.listen({ port: Number(process.env.PORT ?? 3001), host: "127.0.0.1" });
console.log("HEAIR demo available at http://127.0.0.1:3001");
